numeric_vector <- c(1, 2, 3, 4, 5)
char_vector <- c("apple", "banana", "cherry")
logical_vector <- c(TRUE, FALSE, TRUE, FALSE)

cat("Numeric Vector: ", numeric_vector, "\n")
cat("Character Vector: ", char_vector, "\n")
cat("Logical Vector: ", logical_vector, "\n")
cat("Type of Numeric Vector: ", typeof(numeric_vector), "\n")
cat("Type of Character Vector: ", typeof(char_vector), "\n")
cat("Type of Logical Vector: ", typeof(logical_vector), "\n")
